In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import cv2
from PIL import Image
import tensorflow as tf
tf.random.set_seed(5)
from tensorflow import keras
from keras.datasets import mnist
from tensorflow.math import confusion_matrix

In [2]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [3]:
print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

(60000, 28, 28) (60000,) (10000, 28, 28) (10000,)


In [4]:
## scaling the images
## this is done so that the images are in range from 0 to 1
## istead of 0 to 255(max value here)
x_train = x_train/255
x_test = x_test/255

In [5]:
print(x_train[5])

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.    

In [6]:
model = keras.Sequential([
                          keras.layers.Flatten(input_shape=(28,28)),
                          keras.layers.Dense(50, activation='relu'),
                          keras.layers.Dense(50, activation='relu'),
                          keras.layers.Dense(50, activation='relu'),
                          keras.layers.Dense(50, activation='relu'),
                          keras.layers.Dense(50, activation='relu'),
                          keras.layers.Dense(50, activation='relu'),
                          keras.layers.Dense(50, activation='relu'),
                          keras.layers.Dense(50, activation='relu'),
                          keras.layers.Dense(10, activation='sigmoid')
])

In [7]:
model.compile(optimizer='adam',
              loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [8]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 5s 2ms/step - loss: 0.3631 - accuracy: 0.8877
Epoch 2/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1586 - accuracy: 0.9543
Epoch 3/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1270 - accuracy: 0.9630
Epoch 4/10
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1053 - accuracy: 0.9693
Epoch 5/10
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0923 - accuracy: 0.9735
Epoch 6/10
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0827 - accuracy: 0.9764
Epoch 7/10
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0734 - accuracy: 0.9788
Epoch 8/10
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0699 - accuracy: 0.9795
Epoch 9/10
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0611 - accuracy: 0.9821
Epoch 10/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.057

In [9]:
loss, accuracy = model.evaluate(x_test, y_test)
print(accuracy)

313/313 [==============================] - 1s 2ms/step - loss: 0.1080 - accuracy: 0.9723
0.9722999930381775


In [10]:
y_pred = model.predict(x_test)
print(y_test[0], y_pred[0])

7 [6.4725876e-03 6.7594647e-03 4.1069591e-01 1.2047648e-02 6.5992028e-02
 1.6561449e-03 8.5549653e-03 9.9993944e-01 6.7016482e-04 6.9152862e-01]


In [11]:
# converting the prediction probabilities to class label

label_for_first_test_image = np.argmax(y_pred[0])
print(label_for_first_test_image)

7


In [12]:
y_pred_labels = []
for i in y_pred:
    y_pred_labels.append(np.argmax(i))

In [13]:
print(y_pred_labels)

[7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4, 9, 6, 6, 5, 4, 0, 7, 4, 0, 1, 3, 1, 3, 4, 7, 2, 7, 1, 2, 1, 1, 7, 4, 2, 3, 5, 1, 2, 4, 4, 6, 3, 5, 5, 6, 0, 4, 1, 9, 5, 7, 8, 9, 3, 7, 4, 6, 4, 3, 0, 7, 0, 2, 9, 1, 7, 3, 2, 9, 7, 7, 6, 2, 7, 8, 4, 7, 3, 6, 1, 3, 6, 9, 3, 1, 4, 1, 7, 6, 9, 6, 0, 5, 4, 9, 9, 2, 1, 9, 4, 8, 7, 3, 9, 7, 4, 4, 4, 9, 2, 5, 4, 7, 6, 7, 9, 0, 5, 8, 5, 6, 6, 5, 7, 8, 1, 0, 1, 6, 4, 6, 7, 3, 1, 7, 1, 8, 2, 0, 9, 9, 8, 5, 5, 1, 5, 6, 0, 3, 4, 4, 6, 5, 4, 6, 5, 4, 5, 1, 4, 4, 7, 2, 3, 2, 7, 1, 8, 1, 8, 1, 8, 5, 0, 8, 9, 2, 5, 0, 1, 1, 1, 0, 9, 0, 3, 1, 6, 4, 2, 3, 6, 1, 1, 1, 3, 9, 5, 2, 9, 4, 5, 9, 3, 9, 0, 3, 6, 5, 5, 7, 2, 2, 7, 1, 2, 8, 4, 1, 7, 3, 3, 8, 8, 7, 9, 2, 2, 4, 1, 5, 9, 8, 7, 2, 3, 0, 6, 4, 2, 4, 1, 9, 5, 7, 7, 2, 8, 2, 6, 8, 5, 7, 7, 9, 1, 8, 1, 8, 0, 3, 0, 1, 9, 9, 4, 1, 8, 2, 1, 2, 9, 7, 5, 9, 2, 6, 4, 1, 5, 8, 2, 9, 2, 0, 4, 0, 0, 2, 8, 4, 7, 1, 2, 4, 0, 2, 7, 4, 3, 3, 0, 0, 3, 1, 9, 6, 5, 2, 5, 1, 7, 9, 3, 9, 4, 2, 0, 7, 1, 1, 2, 1, 

In [14]:
conf_mat = confusion_matrix(y_test, y_pred_labels)
print(conf_mat)

tf.Tensor(
[[ 957    0    1    1    1    2    2    4    1   11]
 [   0 1121    2    0    0    0    1    1   10    0]
 [   2    3 1000    4    1    2    1    6   12    1]
 [   1    0    1  978    0    5    0    7    7   11]
 [   1    2    1    0  949    0    5    4    3   17]
 [   2    0    0   10    3  855    8    1    6    7]
 [   2    2    1    1   12    3  934    0    3    0]
 [   0    6    8    3    0    0    0 1004    2    5]
 [   3    0    2    4    2    5    1    4  947    6]
 [   1    5    0    0   13    2    1    4    5  978]], shape=(10, 10), dtype=int32)


In [ ]:
plt.figure(figsize=(8,5))
sns.heatmap(conf_mat, annot=True, fmt='d', cmap='Blues')
plt.ylabel('True Labels')
plt.xlabel('Predicted Labels')

In [ ]:
# input_image_path = 'image.jpg'
# input_image = cv2.imread(input_image_path)
# grayscale = cv2.cvtColor(input_image, cv2.COLOR_RGB2GRAY)
# input_image_resize = cv2.resize(grayscale, (28, 28))
# input_image_resize = input_image_resize/255
# image_reshaped = np.reshape(input_image_resize, [1,28,28])
# input_prediction = model.predict(image_reshaped)
# input_pred_label = np.argmax(input_prediction)
# print(input_pred_label)

In [ ]:
# plt.imshow(input_image)